#!/bin/python3

# 2024.11.03, by @zachleach

import time
import sys
import json
import requests
import os
infile = sys.argv[1] if len(sys.argv) > 1 else None

# Load JSON
with open(infile, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Create directory for images
os.makedirs('output', exist_ok=True)

# Download each card's PNG
for card in data:
    base_filename = f"output/{card['set']}_{card['collector_number']}_{card['name'].replace('/', '_').replace(' ', '_')}"
    
    if 'card_faces' in card:
        # Front face
        if 'image_uris' in card['card_faces'][0]:
            print(f"Downloading {card['card_faces'][0]['name']}")
            response = requests.get(card['card_faces'][0]['image_uris']['png'])
            if response.status_code == 200:
                with open(f"{base_filename}_front.png", 'wb') as f:
                    f.write(response.content)
        
        # Back face
        if 'image_uris' in card['card_faces'][1]:
            print(f"Downloading {card['card_faces'][1]['name']}")
            response = requests.get(card['card_faces'][1]['image_uris']['png'])
            if response.status_code == 200:
                with open(f"{base_filename}_back.png", 'wb') as f:
                    f.write(response.content)
        
        time.sleep(0.1)
    
    elif 'image_uris' in card:
        print(f"Downloading {card['name']}")
        response = requests.get(card['image_uris']['png'])
        if response.status_code == 200:
            with open(f"{base_filename}.png", 'wb') as f:
                f.write(response.content)
        
        time.sleep(0.1)
